- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading Web Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes