- name: Disable Mysql 8
  ansible.builtin.shell: dnf module disable mysql -y

- name: Copy file
  ansible.builtin.copy:
    src: mysql.conf
    dest: /etc/yum.repos.d/mysql.repo

- name: install
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: starting mysql
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes
    state: restarted

- name: changing default password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{root_mysql_password}}