- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed


- name: useradd
  ansible.builtin.user:
    name: roboshop

- name: Remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading Web Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes


