- name: Configuring NODEJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash



- name: Include task list in play only if the condition is true
  ansible.builtin.include_tasks: "appprereq.yml"


- name: Install Nodejs Dependies
  community.general.npm:
    path: /app
    state: latest



- name: Include task list in play only if the condition is true
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yaml"
  when: schema_load





